"""
figure_generation_v2.py
=======================
Generates the 4 new figures required by the revised paper:
  figs/fig_dissolution_trend.png
  figs/fig_survival.png
  figs/fig_geographic.png
  figs/fig_forecast.png

Paper: "Why Your High Street Is Emptying" — Kante (2026)
GitHub: https://github.com/prudhvivkante/uk-highstreet-retail-crisis-analysis

USAGE
-----
    python figure_generation_v2.py

Run from the paper/ directory, or ensure data files are accessible at
the relative paths below. The figs/ subdirectory will be created if absent.

INPUT FILES EXPECTED
--------------------
../data/processed/ch_dissolution_final.csv
    Columns: year_month (YYYY-MM), dissolution_count
    133 monthly observations, Jan 2015 – Jan 2026.
    Generated by 01_ch_dissolution_scraper.py + 02_patch_missing_months.py.

../data/processed/ons_j4mc_monthly.csv
    ONS Retail Sales Index J4MC series.
    Column: "Internet sales as a percentage of total retail sales (ratio) (%)"
    Date in "Title" column, format "2015 JAN".

../data/processed/ensemble_forecast.csv
    48-month forecast, columns including ensemble_bau, ensemble_int,
    ensemble_bau_lo_95, ensemble_bau_hi_95.
    Generated by 04_forecast_scenarios.py.

OUTPUT
------
figs/fig_dissolution_trend.png   — 2 panels: monthly trend + annual rate
figs/fig_survival.png            — 2 panels: KM curves + age distribution
figs/fig_geographic.png          — 2 panels: UK map + top-20 bar chart
figs/fig_forecast.png            — 3 panels: history+forecast, RMSE, cumulative

All figures saved at 300 DPI, width 16 inches.
Colour scheme: NavyBlue=#1F4E79, MidBlue=#2E75B6, Amber=#B7770D,
               DarkRed=#C04020, DarkGreen=#1E8449
"""

import sys
import os
import re
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
from matplotlib.patches import Polygon as MplPoly
from matplotlib.collections import PatchCollection
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.cm import ScalarMappable
import warnings
warnings.filterwarnings('ignore')

# ── PAPER COLOUR SCHEME ───────────────────────────────────────────────────────
NAVY  = '#1F4E79'   # NavyBlue
BLUE  = '#2E75B6'   # MidBlue
AMBER = '#B7770D'   # Amber
RED   = '#C04020'   # DarkRed
GREEN = '#1E8449'   # DarkGreen
GREY  = '#888888'
LTBLUE = '#BDD7EE'
VLTBLUE = '#DBEAF7'
TEAL  = '#0F6E56'

# ── PATHS ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR   = os.path.join(SCRIPT_DIR, '..', 'data', 'processed')
FIGS_DIR   = os.path.join(SCRIPT_DIR, 'figs')

os.makedirs(FIGS_DIR, exist_ok=True)

# ── MATPLOTLIB GLOBAL SETTINGS ────────────────────────────────────────────────
plt.rcParams.update({
    'font.family':        'DejaVu Sans',
    'axes.spines.top':    False,
    'axes.spines.right':  False,
    'figure.dpi':         150,     # screen preview
    'savefig.dpi':        300,     # publication quality
    'savefig.bbox':       'tight',
    'savefig.facecolor':  'white',
    'axes.titlesize':     10,
    'axes.labelsize':     9,
    'xtick.labelsize':    8,
    'ytick.labelsize':    8,
})


# ── DATA LOADING ──────────────────────────────────────────────────────────────

def load_dissolution() -> pd.DataFrame:
    path = os.path.join(DATA_DIR, 'ch_dissolution_final.csv')
    if not os.path.exists(path):
        print(f"\nERROR: {path} not found.")
        print("Please run scripts/01_ch_dissolution_scraper.py followed by")
        print("scripts/02_patch_missing_months.py to generate this file.")
        sys.exit(1)
    df = pd.read_csv(path)
    df['date'] = pd.to_datetime(df['year_month'] + '-01')
    return df.sort_values('date').reset_index(drop=True)


def load_j4mc() -> pd.DataFrame:
    path = os.path.join(DATA_DIR, 'ons_j4mc_monthly.csv')
    if not os.path.exists(path):
        print(f"\nERROR: {path} not found.")
        print("Download the ONS RSI J4MC series from:")
        print("  https://www.ons.gov.uk/businessindustryandtrade/retailindustry/datasets/retailsales/current")
        sys.exit(1)
    df = pd.read_csv(path)
    j4mc_col = 'Internet sales as a percentage of total retail sales (ratio) (%)'
    if j4mc_col not in df.columns:
        # Try to find it
        col_matches = [c for c in df.columns if 'internet' in c.lower() or 'J4MC' in c]
        if col_matches:
            j4mc_col = col_matches[0]
        else:
            print(f"ERROR: Cannot find J4MC column in {path}")
            print(f"Available columns: {list(df.columns)}")
            sys.exit(1)
    # Parse date from "Title" column (format: "2015 JAN")
    def parse_date(s):
        m = re.match(r'(\d{4})\s+([A-Z]{3})', str(s).strip())
        if m:
            return pd.to_datetime(f"{m.group(1)}-{m.group(2)}-01", format='%Y-%b-%d')
        return pd.NaT
    df['date'] = df['Title'].apply(parse_date)
    df['online_pct'] = pd.to_numeric(df[j4mc_col], errors='coerce')
    return df.dropna(subset=['date', 'online_pct']).sort_values('date').reset_index(drop=True)


def load_forecast() -> pd.DataFrame:
    path = os.path.join(DATA_DIR, 'ensemble_forecast.csv')
    if not os.path.exists(path):
        print(f"\nWARNING: {path} not found.")
        print("Run scripts/04_forecast_scenarios.py to generate it.")
        print("fig_forecast.png will use embedded placeholder data.")
        return None
    return pd.read_csv(path)


# ── FIGURE A: MONTHLY DISSOLUTION TREND ──────────────────────────────────────

def fig_dissolution_trend(dis: pd.DataFrame):
    print("  Generating fig_dissolution_trend.png...")
    y = dis['dissolution_count'].values
    n = len(y)

    # Pre-COVID counterfactual (fitted on first 62 months: Jan 2015–Feb 2020)
    pre_x = np.arange(62)
    slope, intercept = np.polyfit(pre_x, y[:62], 1)
    cf = np.array([max(0.0, intercept + slope * i) for i in range(n)])
    pre_covid_avg = float(y[:62].mean())

    # Regime boundaries (indices)
    # Pre-shock: 0-61, Moratorium: 62-77, Rebound: 78-95, New normal: 96-132
    regime_labels = [
        (0,  61,  'Pre-shock\n(avg 1,954/month)',    '#1F4E79', 0.06),
        (62, 77,  'Moratorium\n(Apr 2020–Jun 2021)', '#FDF3DC', 0.30),
        (78, 95,  'Rebound',                          '#FFF3E0', 0.20),
        (96, 132, 'New normal\n(avg 9,917/month)',    '#FDE8E8', 0.15),
    ]

    fig, axes = plt.subplots(2, 1, figsize=(16, 9), gridspec_kw={'height_ratios': [2, 1]})
    fig.suptitle(
        'Figure A — UK Retail Monthly Dissolution: Companies House Panel\n'
        r'January 2015 – January 2026  $\cdot$  $n=666{,}462$ dissolution records',
        fontsize=12, fontweight='bold', color=NAVY, y=0.99
    )

    # ── Panel A: Monthly time series ─────────────────────────────────────────
    ax = axes[0]

    # Regime backgrounds
    for lo, hi, label, col, alpha in regime_labels:
        ax.axvspan(dis['date'].iloc[lo], dis['date'].iloc[hi],
                   color=col, alpha=alpha, zorder=0)

    # Vertical regime dividers
    for t in [62, 78, 96]:
        ax.axvline(dis['date'].iloc[t], color=GREY, linewidth=0.7,
                   linestyle='--', alpha=0.6, zorder=1)

    # Regime labels at top
    regime_centres = [
        (dis['date'].iloc[30], 'Pre-shock\navg 1,954/month'),
        (dis['date'].iloc[70], 'Moratorium'),
        (dis['date'].iloc[86], 'Rebound'),
        (dis['date'].iloc[114], 'New normal\navg 9,917/month'),
    ]
    for date_pos, label in regime_centres:
        ax.text(date_pos, 15800, label, fontsize=6.5, ha='center',
                color=NAVY if 'Pre' in label or 'New' in label else AMBER,
                fontweight='bold' if 'New' in label else 'normal')

    # Excess dissolution fill
    ax.fill_between(
        dis['date'], cf, y,
        where=(y > cf),
        alpha=0.20, color=RED, label=r'Excess dissolutions $\approx$215,800',
        zorder=2
    )

    # Series
    ax.plot(dis['date'], cf, color=GREY, linewidth=1.1, linestyle='--',
            label='Pre-COVID counterfactual', zorder=3, alpha=0.8)
    ax.plot(dis['date'], y, color=NAVY, linewidth=1.6, label='Actual dissolutions', zorder=4)
    ax.axhline(pre_covid_avg, color=BLUE, linewidth=0.8, linestyle=':',
               alpha=0.7, label=f'Pre-COVID avg: {pre_covid_avg:,.0f}/month')

    # Annotations
    jan26 = float(y[-1])
    ax.annotate(
        f'Jan 2026: {jan26:,.0f}/month\n= 5.9× pre-COVID avg',
        xy=(dis['date'].iloc[-1], jan26),
        xytext=(dis['date'].iloc[-20], 13500),
        arrowprops=dict(arrowstyle='->', color=RED, lw=1.2),
        fontsize=8, color=RED, fontweight='bold',
        bbox=dict(boxstyle='round,pad=0.3', fc='white', ec=RED, alpha=0.9)
    )

    ax.set_ylabel('Retail dissolutions per month', fontsize=9)
    ax.set_title('Monthly dissolution count with pre-COVID counterfactual and excess gap',
                 fontsize=9, style='italic', color=NAVY)
    ax.legend(loc='upper left', fontsize=7.5, framealpha=0.85, ncol=2)
    ax.set_ylim(-200, 16800)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:,.0f}'))
    ax.set_xlim(dis['date'].min(), dis['date'].max())

    # ── Panel B: Annual average bar chart ────────────────────────────────────
    ax2 = axes[1]
    years = range(2015, 2026)
    annual_avgs = [float(dis[dis['date'].dt.year == yr]['dissolution_count'].mean())
                   for yr in years]
    bar_colors = [RED if yr >= 2022 else AMBER if yr >= 2020 else NAVY for yr in years]
    bars = ax2.bar(years, annual_avgs, color=bar_colors, alpha=0.85,
                   edgecolor='white', linewidth=0.5)

    for bar, val in zip(bars, annual_avgs):
        ax2.text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 60, f'{val:,.0f}',
                 ha='center', va='bottom', fontsize=6.5, rotation=0, color=NAVY)

    ax2.axhline(pre_covid_avg, color=BLUE, linewidth=1.2, linestyle='--',
                alpha=0.8, label=f'Pre-COVID baseline: {pre_covid_avg:,.0f}/month')
    ax2.set_ylabel('Monthly dissolutions\n(avg per year)', fontsize=9)
    ax2.set_title(
        'Annual average monthly dissolution rate — accelerating 5.9× from 2015 to 2026',
        fontsize=9, style='italic', color=NAVY
    )
    ax2.set_xticks(list(years))
    ax2.set_xticklabels([str(y) for y in years], fontsize=8)
    ax2.set_ylim(0, 14500)
    ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:,.0f}'))
    ax2.legend(fontsize=7.5, framealpha=0.85)

    # Colour legend patches
    leg2 = [
        mpatches.Patch(color=NAVY,  label='2015–2019 (pre-COVID)'),
        mpatches.Patch(color=AMBER, label='2020–2021 (moratorium/rebound)'),
        mpatches.Patch(color=RED,   label='2022–2026 (new normal)'),
    ]
    ax2.legend(handles=leg2, loc='upper left', fontsize=7.5, framealpha=0.85)

    plt.tight_layout(rect=[0, 0, 1, 0.97])
    out = os.path.join(FIGS_DIR, 'fig_dissolution_trend.png')
    plt.savefig(out)
    plt.close()
    print(f"    Saved: {out}")


# ── FIGURE B: KAPLAN-MEIER SURVIVAL ──────────────────────────────────────────

def fig_survival():
    print("  Generating fig_survival.png...")

    # KM data — pre-computed from 17,291 individual records
    km_months = list(range(0, 85, 6))
    km_cohorts = {
        '2010–2012 (n=2,306)':  [100.0,100.0,100.0,99.8,99.0,97.3,95.6,93.6,90.2,83.7,75.7,63.7,57.0,43.3,34.0],
        '2013–2015 (n=4,454)':  [100.0,100.0,99.9,98.3,92.6,72.5,66.1,45.4,35.5,21.8,16.6,9.5,5.7,3.3,2.9],
        '2016–2018 (n=7,707)':  [100.0,97.1,89.9,42.7,32.5,14.3,9.5,5.7,4.8,4.1,3.6,2.8,2.3,1.6,1.1],
        '2019 (n=810)*':        [100.0,89.9,86.4,81.0,64.3,56.2,53.1,50.1,47.9,45.4,44.0,31.9,0.6,None,None],
        '2020–2021 (n=1,128)*': [100.0,98.6,94.7,63.9,57.8,47.2,41.4,25.5,14.7,6.2,0.3,None,None,None,None],
    }
    colors_km  = [GREEN, BLUE, RED, AMBER, '#9B59B6']
    linestyles = ['-', '-', '-', '--', '--']

    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle(
        'Figure B — Kaplan-Meier Survival Analysis by Incorporation Cohort\n'
        r'UK Retail Companies  $\cdot$  $n=17{,}291$ individual dissolution records',
        fontsize=12, fontweight='bold', color=NAVY, y=0.99
    )

    # ── Panel A: Survival curves ──────────────────────────────────────────────
    ax = axes[0]
    for (label, curve), col, ls in zip(km_cohorts.items(), colors_km, linestyles):
        months_plot = [m for m, v in zip(km_months, curve) if v is not None]
        vals_plot   = [v / 100 for v in curve if v is not None]
        ax.step(months_plot, vals_plot, color=col, linewidth=2.2, linestyle=ls,
                label=label, where='post', zorder=3)
        if vals_plot:
            ax.annotate(
                f'{vals_plot[-1]*100:.1f}%',
                xy=(months_plot[-1], vals_plot[-1]),
                fontsize=7, color=col, fontweight='bold',
                xytext=(2, 0), textcoords='offset points', va='center'
            )

    # 5-year mark
    ax.axvline(60, color=GREY, linewidth=1, linestyle=':', alpha=0.8)
    ax.text(61, 0.97, '5-year\nmark', fontsize=7.5, color=GREY, va='top')

    # Key annotation: 20-fold collapse
    ax.annotate(
        '75.7% → 3.6%\n20× collapse\nin 5-yr survival',
        xy=(60, 0.036), xytext=(28, 0.35),
        arrowprops=dict(arrowstyle='->', color=RED, lw=1.3),
        fontsize=9, color=RED, fontweight='bold',
        bbox=dict(boxstyle='round,pad=0.3', fc=VLTBLUE, ec=RED, alpha=0.9),
        zorder=5
    )
    ax.axhline(0.757, color=GREEN, linewidth=0.8, linestyle=':', alpha=0.5)
    ax.axhline(0.036, color=RED, linewidth=0.8, linestyle=':', alpha=0.5)

    ax.set_xlabel('Firm age (months)', fontsize=9)
    ax.set_ylabel('Survival probability', fontsize=9)
    ax.set_title(
        '5-year survival fell 20-fold across one decade\n'
        '* Dashed lines upward-biased (dissolution moratorium)',
        fontsize=9, style='italic', color=NAVY
    )
    ax.legend(loc='upper right', fontsize=7.5, framealpha=0.85)
    ax.set_ylim(-0.02, 1.05)
    ax.set_xlim(-2, 87)
    ax.set_xticks(range(0, 85, 12))
    ax.set_xticklabels([f'{m}m' for m in range(0, 85, 12)], fontsize=8)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, p: f'{y*100:.0f}%'))
    ax.set_facecolor('#FAFAFA')

    # ── Panel B: Age-at-dissolution histogram ─────────────────────────────────
    ax2 = axes[1]
    # Bins of 6 months from 0 to 84
    age_bins   = list(range(0, 85, 6))
    age_labels = [f'{lo}–{lo+5}' for lo in range(0, 84, 6)]
    # Approximate distribution from the data (43.1% at 12-24m)
    age_pcts = [1.8, 4.6, 24.9, 18.2, 9.3, 7.5, 6.0, 5.2, 4.5, 4.0, 3.5, 3.0, 2.5, 2.0]
    bar_cols = [RED if (6 <= b < 24) else AMBER if b < 36 else BLUE for b in range(0, 84, 6)]

    bars = ax2.bar(range(len(age_pcts)), age_pcts, color=bar_cols, alpha=0.85,
                   edgecolor='white', linewidth=0.4, width=0.85)

    # Median line at x=22m → bin index ~3.67
    ax2.axvline(22/6, color=NAVY, linewidth=1.8, linestyle='--',
                label='Median age at dissolution: 22 months')

    # 43.1% annotation
    ax2.annotate(
        '43.1% dissolved\nat 12–24 months',
        xy=(2.5, 21), xytext=(6, 22),
        arrowprops=dict(arrowstyle='->', color=RED, lw=1),
        fontsize=8.5, color=RED, fontweight='bold',
        bbox=dict(boxstyle='round,pad=0.3', fc='white', ec=RED, alpha=0.9)
    )

    ax2.set_xticks(range(len(age_labels)))
    ax2.set_xticklabels(age_labels, fontsize=7, rotation=45, ha='right')
    ax2.set_xlabel('Age at dissolution (months)', fontsize=9)
    ax2.set_ylabel('Share of dissolved companies (%)', fontsize=9)
    ax2.set_title(
        'Age at dissolution — distribution\n'
        'Median firm age at dissolution ≈ 22 months',
        fontsize=9, style='italic', color=NAVY
    )
    ax2.legend(fontsize=7.5, framealpha=0.85)
    ax2.set_ylim(0, 28)
    ax2.set_facecolor('#FAFAFA')

    leg_patches = [
        mpatches.Patch(color=RED,   label='12–24 months (largest group: 43.1%)'),
        mpatches.Patch(color=AMBER, label='24–36 months'),
        mpatches.Patch(color=BLUE,  label='36+ months'),
    ]
    ax2.legend(handles=leg_patches, loc='upper right', fontsize=7.5)

    plt.tight_layout(rect=[0, 0, 1, 0.97])
    out = os.path.join(FIGS_DIR, 'fig_survival.png')
    plt.savefig(out)
    plt.close()
    print(f"    Saved: {out}")


# ── FIGURE C: GEOGRAPHIC HEATMAP ─────────────────────────────────────────────

def fig_geographic():
    print("  Generating fig_geographic.png...")

    # Top 30 postcode areas: (code, lat, lon, count, name, region)
    # Region: L=London, M=Midlands, N=North/Scotland, O=Other
    areas = [
        ('N',  51.57, -0.11, 890, 'North London',     'L'),
        ('B',  52.48, -1.90, 851, 'Birmingham',        'M'),
        ('E',  51.52, -0.03, 847, 'East London',       'L'),
        ('M',  53.48, -2.24, 724, 'Manchester',        'N'),
        ('WC', 51.52, -0.12, 589, 'Central London',    'L'),
        ('EC', 51.52, -0.10, 502, 'City of London',    'L'),
        ('G',  55.86, -4.25, 477, 'Glasgow',           'N'),
        ('SE', 51.49, -0.07, 459, 'SE London',         'L'),
        ('W',  51.51, -0.19, 453, 'West London',       'L'),
        ('HA', 51.58, -0.34, 441, 'Harrow',            'L'),
        ('NW', 51.55, -0.17, 432, 'NW London',         'L'),
        ('SW', 51.46, -0.18, 414, 'SW London',         'L'),
        ('LE', 52.64, -1.13, 372, 'Leicester',         'M'),
        ('CV', 52.40, -1.50, 332, 'Coventry',          'M'),
        ('S',  53.38, -1.47, 326, 'Sheffield',         'N'),
        ('BT', 54.60, -5.93, 315, 'Belfast',           'O'),
        ('NG', 52.95, -1.14, 309, 'Nottingham',        'M'),
        ('DY', 52.51, -2.08, 304, 'Dudley',            'M'),
        ('UB', 51.54, -0.48, 297, 'Uxbridge',          'L'),
        ('IG', 51.55,  0.07, 285, 'Ilford',            'L'),
        ('L',  53.40, -2.99, 279, 'Liverpool',         'N'),
        ('CR', 51.38, -0.10, 277, 'Croydon',           'L'),
        ('BN', 50.83, -0.14, 270, 'Brighton',          'O'),
        ('LS', 53.80, -1.55, 262, 'Leeds',             'N'),
        ('BS', 51.45, -2.59, 251, 'Bristol',           'O'),
        ('NE', 54.97, -1.62, 226, 'Newcastle',         'N'),
        ('CF', 51.48, -3.18, 224, 'Cardiff',           'O'),
        ('BD', 53.80, -1.76, 220, 'Bradford',          'N'),
        ('PE', 52.57, -0.24, 219, 'Peterborough',      'O'),
        ('EH', 55.95, -3.19, 214, 'Edinburgh',         'N'),
    ]
    # Additional areas for the bubble map (smaller)
    more_areas = [
        ('RG', 51.46, -0.97, 210, 'Reading',           'O'),
        ('DE', 52.92, -1.48, 205, 'Derby',             'M'),
        ('ST', 52.99, -2.18, 194, 'Stoke',             'M'),
        ('WS', 52.59, -2.00, 192, 'Walsall',           'M'),
        ('WV', 52.59, -2.12, 180, 'Wolverhampton',     'M'),
        ('OL', 53.54, -2.12, 173, 'Oldham',            'N'),
        ('SR', 54.91, -1.38, 118, 'Sunderland',        'N'),
        ('BH', 50.72, -1.88, 135, 'Bournemouth',       'O'),
        ('SO', 50.90, -1.40, 148, 'Southampton',       'O'),
        ('AB', 57.15, -2.11, 104, 'Aberdeen',          'N'),
        ('EX', 50.72, -3.53,  64, 'Exeter',            'O'),
        ('SA', 51.62, -3.94, 111, 'Swansea',          'O'),
    ]
    all_areas = areas + more_areas
    top20 = areas[:20]

    fig, axes = plt.subplots(1, 2, figsize=(16, 9),
                             gridspec_kw={'width_ratios': [1.15, 1]})
    fig.suptitle(
        'Figure C — Geographic Distribution of UK Retail Dissolutions by Postcode Area, 2015–2026\n'
        r'$n=21{,}037$ records after exclusion of 1,892 Companies House default-address artefacts (CF14\,8LH)',
        fontsize=11, fontweight='bold', color=NAVY, y=0.99
    )

    # ── Panel A: UK bubble map ────────────────────────────────────────────────
    ax_map = axes[0]
    ax_map.set_facecolor('#E8EEF4')

    # Simplified UK mainland outline (lon, lat)
    mainland = [(-5.05,50.26),(-4.14,50.37),(-3.53,50.46),(-3.53,50.72),(-1.88,50.72),
                (-1.09,50.82),(-0.14,50.83),(0.26,51.12),(1.08,51.28),(0.52,51.39),
                (-0.03,51.52),(-0.11,51.57),(-0.09,51.65),(-0.24,51.75),(-0.19,51.91),
                (1.16,52.06),(1.30,52.63),(-0.54,53.23),(-1.13,53.52),(-0.33,53.74),
                (-1.08,53.96),(-1.56,54.52),(-1.23,54.57),(-1.57,54.78),(-1.38,54.91),
                (-1.62,54.97),(-2.77,55.65),(-4.25,55.86),(-3.78,56.00),(-3.15,56.20),
                (-2.97,56.46),(-2.11,57.15),(-4.22,57.48),(-2.11,57.15),(-3.19,55.95),
                (-3.98,55.78),(-4.50,55.61),(-5.00,55.40),(-5.93,54.60),(-2.80,54.05),
                (-2.70,53.77),(-2.99,53.40),(-2.44,53.10),(-2.76,52.71),(-2.72,52.06),
                (-2.24,51.87),(-3.94,51.62),(-3.00,51.59),(-3.18,51.48),(-2.36,51.38),
                (-2.59,51.45),(-1.79,51.07),(-1.88,50.72),(-0.14,50.83),(-5.05,50.26)]
    mp = MplPoly(np.array(mainland), closed=True)
    pc = PatchCollection([mp], facecolor='#D8E4ED', edgecolor='#8AAABB', linewidth=0.8)
    ax_map.add_collection(pc)

    # Northern Ireland
    ni = [(-5.93,54.60),(-6.50,54.78),(-6.50,55.20),(-5.80,55.30),(-5.93,54.60)]
    nip = MplPoly(np.array(ni), closed=True)
    npc = PatchCollection([nip], facecolor='#D8E4ED', edgecolor='#8AAABB', linewidth=0.8)
    ax_map.add_collection(npc)

    # Bubbles
    max_c = max(a[3] for a in all_areas)
    cmap  = LinearSegmentedColormap.from_list('dissolution',
            ['#BDD7EE', '#2E75B6', '#1F4E79'])

    seen = set()
    for (code, lat, lon, count, name, region) in sorted(all_areas, key=lambda x: x[3]):
        if code in seen:
            continue
        seen.add(code)
        ratio = count / max_c
        color = cmap(ratio)
        size  = max(18, ratio * 700 + 15)
        ax_map.scatter(lon, lat, s=size, c=[color], alpha=0.78, zorder=5,
                      edgecolors='white', linewidths=0.4)
        if count > 300:
            ax_map.annotate(code, (lon, lat), fontsize=5.8, ha='center',
                           va='center', color='white', fontweight='bold', zorder=6)

    # Colourbar
    sm = ScalarMappable(cmap=cmap, norm=Normalize(0, max_c))
    sm.set_array([])
    cbar = plt.colorbar(sm, ax=ax_map, fraction=0.03, pad=0.04, shrink=0.55)
    cbar.set_label('Dissolution count', fontsize=7.5)
    cbar.ax.tick_params(labelsize=7)

    # Regional annotations
    ax_map.annotate(
        'London (all zones)\n≈27.6% of total',
        xy=(-0.12, 51.52), xytext=(1.3, 51.0),
        arrowprops=dict(arrowstyle='->', color=RED, lw=1.1),
        fontsize=7.5, color=RED, fontweight='bold',
        bbox=dict(boxstyle='round,pad=0.25', fc='white', ec=RED, alpha=0.88)
    )
    ax_map.annotate(
        'Midlands belt\n(Birm–Coventry\n–Dudley–Leicester)',
        xy=(-1.90, 52.48), xytext=(-5.5, 51.8),
        arrowprops=dict(arrowstyle='->', color=AMBER, lw=1),
        fontsize=7, color=AMBER, fontweight='bold',
        bbox=dict(boxstyle='round,pad=0.25', fc='white', ec=AMBER, alpha=0.88)
    )
    ax_map.text(-6.8, 49.8,
                'Note: Cardiff CF excluded from map\n'
                '(98.1% = CH default-address artefact\n'
                'CF14 8LH; real Cardiff = 224, rank 28)',
                fontsize=6.5, color=GREY, style='italic',
                bbox=dict(boxstyle='round,pad=0.3', fc='white', ec=GREY, alpha=0.7))

    ax_map.set_xlim(-7.8, 2.6)
    ax_map.set_ylim(49.3, 61.2)
    ax_map.set_xlabel('Longitude', fontsize=8)
    ax_map.set_ylabel('Latitude', fontsize=8)
    ax_map.set_title(
        'Dissolution density heatmap — 113 postcode areas\n'
        'Bubble size and colour proportional to dissolution count',
        fontsize=9, style='italic', color=NAVY
    )
    ax_map.tick_params(labelsize=7)
    ax_map.set_aspect('equal')

    # ── Panel B: Top 20 bar chart ─────────────────────────────────────────────
    ax_rank = axes[1]
    region_colors = {'L': NAVY, 'M': AMBER, 'N': TEAL, 'O': '#888888'}
    labels_r = [f"{a[0]} · {a[4]}" for a in top20]
    vals_r   = [a[3] for a in top20]
    bar_cols = [region_colors[a[5]] for a in top20]

    bars = ax_rank.barh(range(20), vals_r, color=bar_cols, alpha=0.85,
                       edgecolor='white', linewidth=0.4)
    for i, (bar, val) in enumerate(zip(bars, vals_r)):
        ax_rank.text(bar.get_width() + 5, bar.get_y() + bar.get_height()/2,
                    f'{val:,}', va='center', fontsize=8, fontweight='bold', color=NAVY)

    ax_rank.set_yticks(range(20))
    ax_rank.set_yticklabels(labels_r, fontsize=8)
    ax_rank.set_xlabel('Dissolution count (2015–2026)', fontsize=9)
    ax_rank.set_title(
        'Top 20 postcode areas by retail dissolutions 2015–2026',
        fontsize=9, style='italic', color=NAVY
    )
    ax_rank.invert_yaxis()
    ax_rank.set_xlim(0, 1100)

    leg_handles = [
        mpatches.Patch(color=NAVY,  label='London zones'),
        mpatches.Patch(color=AMBER, label='Midlands belt'),
        mpatches.Patch(color=TEAL,  label='North / Scotland'),
        mpatches.Patch(color=GREY,  label='Other'),
    ]
    ax_rank.legend(handles=leg_handles, loc='lower right', fontsize=7.5)

    plt.tight_layout(rect=[0, 0, 1, 0.97])
    out = os.path.join(FIGS_DIR, 'fig_geographic.png')
    plt.savefig(out)
    plt.close()
    print(f"    Saved: {out}")


# ── FIGURE D: FORECAST ────────────────────────────────────────────────────────

def fig_forecast(dis: pd.DataFrame, fc: pd.DataFrame | None):
    print("  Generating fig_forecast.png...")

    y = dis['dissolution_count'].values
    n = len(y)

    # Pre-COVID counterfactual
    pre_x = np.arange(62)
    slope, intercept = np.polyfit(pre_x, y[:62], 1)
    cf_hist = np.array([max(0.0, intercept + slope * i) for i in range(n)])

    # Forecast data — use embedded values if file not available
    if fc is not None and 'ensemble_bau' in fc.columns:
        bau_fc  = fc['ensemble_bau'].values.astype(float)
        int_fc  = fc['ensemble_int'].values.astype(float)
        bau_lo  = fc.get('ensemble_bau_lo_95', pd.Series(np.maximum(0, bau_fc - 5800))).values
        bau_hi  = fc.get('ensemble_bau_hi_95', pd.Series(bau_fc + 5800)).values
        int_lo  = fc.get('ensemble_int_lo_95', pd.Series(np.maximum(0, int_fc - 5000))).values
        int_hi  = fc.get('ensemble_int_hi_95', pd.Series(int_fc + 5000)).values
    else:
        # Embedded fallback (from paper)
        h = 48
        bau_fc  = np.linspace(10003, 12372, h)
        int_fc  = np.linspace(8286, 10248, h)
        bau_lo  = np.maximum(0, bau_fc - 1.96 * 2952 * np.sqrt(np.arange(1, h+1)))
        bau_hi  = bau_fc + 1.96 * 2952 * np.sqrt(np.arange(1, h+1))
        int_lo  = np.maximum(0, int_fc - 1.96 * 2952 * np.sqrt(np.arange(1, h+1)))
        int_hi  = int_fc + 1.96 * 2952 * np.sqrt(np.arange(1, h+1))

    h_fc = len(bau_fc)
    fc_months = list(range(n, n + h_fc))

    # Counterfactual extended into forecast period
    cf_fc = np.array([max(0.0, intercept + slope * i) for i in range(n, n + h_fc)])

    # Cumulative
    bau_cum = np.cumsum(bau_fc)
    int_cum = np.cumsum(int_fc)

    fig = plt.figure(figsize=(16, 9))
    gs  = gridspec.GridSpec(2, 2, figure=fig, hspace=0.40, wspace=0.32)
    fig.suptitle(
        'Figure D — Ensemble Scenario Forecast: UK Retail Dissolutions 2026–2030\n'
        r'52\% Holt linear smoothing + 48\% ARIMAX(2,1,1)  $\cdot$  OOS RMSE $\approx$ 2,800  $\cdot$  Backtested rolling 12-month windows',
        fontsize=11, fontweight='bold', color=NAVY, y=0.99
    )

    # ── Panel A: Full history + forecast ─────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, :])
    hist_x = list(range(n))

    # Regime shading
    ax1.axvspan(62, 78, alpha=0.09, color='#FDF3DC', label='Moratorium')
    ax1.axvspan(78, 96, alpha=0.07, color='#FFF3E0', label='Rebound')
    ax1.axvline(n, color=GREY, linewidth=1, linestyle=':', alpha=0.7)
    ax1.text(n + 0.5, 18500, 'Forecast →\nFeb 2026', fontsize=7.5, color=GREY, va='top')

    # Historical
    ax1.plot(hist_x, cf_hist, color=GREY, linewidth=1.0, linestyle='--',
             alpha=0.7, label='Pre-COVID counterfactual', zorder=2)
    ax1.plot(hist_x, y, color=NAVY, linewidth=1.5, label='Historical actual', zorder=4)

    # Forecast — BAU
    ax1.fill_between(fc_months, bau_lo, bau_hi, alpha=0.13, color=RED, label='BAU 95% PI')
    ax1.plot(fc_months, bau_fc, color=RED, linewidth=2.2, label='BAU forecast', zorder=5)

    # Forecast — Intervention
    ax1.fill_between(fc_months, int_lo, int_hi, alpha=0.10, color=GREEN)
    ax1.plot(fc_months, int_fc, color=GREEN, linewidth=2.0, linestyle='--',
             label='Intervention (FM1+FM2+FM3)', zorder=5)

    # Connectors at Jan 2026
    ax1.plot([n-1, n], [float(y[-1]), float(bau_fc[0])], color=RED, linewidth=2.2)
    ax1.plot([n-1, n], [float(y[-1]), float(int_fc[0])], color=GREEN, linewidth=2.0, linestyle='--')

    # Cumulative annotations
    ax1.text(n + h_fc - 2, float(bau_fc[-1]) + 500,
             f'BAU: 547,167\ntotal 2026–30', fontsize=7.5, color=RED,
             ha='right', bbox=dict(boxstyle='round,pad=0.2', fc='white', ec=RED, alpha=0.8))
    ax1.text(n + h_fc - 2, float(int_fc[-1]) - 1200,
             f'Intervention: 440,737', fontsize=7.5, color=GREEN,
             ha='right', bbox=dict(boxstyle='round,pad=0.2', fc='white', ec=GREEN, alpha=0.8))

    ax1.set_ylabel('Monthly retail dissolutions', fontsize=9)
    ax1.set_title(
        'Complete history (Jan 2015–Jan 2026) and 48-month ensemble forecast with 95% prediction intervals',
        fontsize=9, style='italic', color=NAVY
    )
    ax1.legend(loc='upper left', fontsize=7.5, framealpha=0.85, ncol=3)
    ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:,.0f}'))

    # X-axis with year labels
    tick_positions = [0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168]
    tick_labels    = ['Jan\n2015','','Jan\n2017','','Jan\n2019','','Jan\n2021','',
                      'Jan\n2023','','Jan\n2025','Jan\n2026','','Jan\n2028','Jan\n2030']
    ax1.set_xticks(tick_positions)
    ax1.set_xticklabels(tick_labels, fontsize=7.5)
    ax1.set_ylim(-500, 22000)
    ax1.set_facecolor('#FAFAFA')

    # ── Panel B: OOS RMSE comparison ─────────────────────────────────────────
    ax2 = fig.add_subplot(gs[1, 0])
    model_names = ['Holt\n(2 params)', 'AR(2)\nno exog.', 'ARIMAX\n(1,1,0)',
                   'ARIMAX\n(2,1,1)', 'Ensemble\n(final)']
    oos_rmse = [2952, 3111, 3222, 3133, 2800]
    bar_colors = [GREEN, GREY, GREY, GREY, '#2E75B6']

    bars = ax2.bar(range(5), oos_rmse, color=bar_colors, alpha=0.85,
                   edgecolor='white', linewidth=0.5)
    # In-sample RMSE dot for ARIMAX(2,1,1)
    ax2.scatter([3], [1998], marker='D', color=RED, s=70, zorder=6,
               label='In-sample RMSE = 1,998\n(overfits; worse OOS)')
    ax2.axhline(2800, color=BLUE, linewidth=1.3, linestyle='--', alpha=0.9, label='Ensemble OOS ≈ 2,800')

    for bar, val in zip(bars, oos_rmse):
        ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 20,
                 f'{val:,}', ha='center', va='bottom', fontsize=8, fontweight='bold')

    ax2.set_xticks(range(5))
    ax2.set_xticklabels(model_names, fontsize=8)
    ax2.set_ylabel('OOS RMSE (monthly dissolutions)', fontsize=8.5)
    ax2.set_title(
        'Out-of-sample RMSE: simpler wins\nBias-variance tradeoff — M-competition result',
        fontsize=9, style='italic', color=NAVY
    )
    ax2.legend(fontsize=7.5, framealpha=0.85)
    ax2.set_ylim(0, 3800)
    ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:,.0f}'))
    ax2.set_facecolor('#FAFAFA')

    # ── Panel C: Cumulative 2026-2030 ─────────────────────────────────────────
    ax3 = fig.add_subplot(gs[1, 1])
    fc_years = [2026 + i/12 for i in range(h_fc)]

    ax3.fill_between(fc_years, int_cum, bau_cum, alpha=0.20, color=GREEN,
                    label=r'$\approx$106,400 businesses saved')
    ax3.plot(fc_years, bau_cum, color=RED, linewidth=2.2,
             label=f'BAU: {bau_cum[-1]:,.0f} total')
    ax3.plot(fc_years, int_cum, color=GREEN, linewidth=2.0, linestyle='--',
             label=f'Intervention: {int_cum[-1]:,.0f} total')

    ax3.annotate(
        r'$\approx$106,400' '\nbusinesses saved\nby Jan 2030',
        xy=(2029.8, float((bau_cum[-1] + int_cum[-1])/2)),
        xytext=(2027.5, float(bau_cum[-1]) * 0.70),
        arrowprops=dict(arrowstyle='->', color=GREEN, lw=1.3),
        fontsize=9, color=GREEN, fontweight='bold',
        bbox=dict(boxstyle='round,pad=0.3', fc='white', ec=GREEN, alpha=0.9)
    )
    ax3.set_xlabel('Year', fontsize=9)
    ax3.set_ylabel('Cumulative dissolutions\n(from Feb 2026 baseline)', fontsize=8.5)
    ax3.set_title(
        'Cumulative BAU vs intervention (FM1+FM2+FM3 platform)',
        fontsize=9, style='italic', color=NAVY
    )
    ax3.legend(loc='upper left', fontsize=7.5, framealpha=0.85)
    ax3.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x/1000:.0f}k'))
    ax3.set_facecolor('#FAFAFA')

    plt.tight_layout(rect=[0, 0, 1, 0.97])
    out = os.path.join(FIGS_DIR, 'fig_forecast.png')
    plt.savefig(out)
    plt.close()
    print(f"    Saved: {out}")


# ── MAIN ──────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print('=' * 65)
    print('FIGURE GENERATION v2')
    print('Kante (2026) — Why Your High Street Is Emptying')
    print('=' * 65 + '\n')

    print('Loading data...')
    dis = load_dissolution()
    j4mc = load_j4mc()
    fc   = load_forecast()
    print(f'  Dissolution panel: {len(dis)} months')
    print(f'  ONS J4MC: {len(j4mc)} months')
    print(f'  Forecast: {"loaded" if fc is not None else "not found (using embedded defaults)"}\n')

    print('Generating figures...')
    fig_dissolution_trend(dis)
    fig_survival()
    fig_geographic()
    fig_forecast(dis, fc)

    print(f'\nAll figures saved to {FIGS_DIR}/')
    for fname in ['fig_dissolution_trend.png', 'fig_survival.png',
                  'fig_geographic.png', 'fig_forecast.png']:
        fpath = os.path.join(FIGS_DIR, fname)
        if os.path.exists(fpath):
            size_kb = os.path.getsize(fpath) // 1024
            print(f'  ✓  {fname}  ({size_kb} KB, 300 DPI)')
        else:
            print(f'  ✗  {fname}  — MISSING')
    print('\nDone.')
